name: 'Setup Cygwin'
description: 'Install Cygwin'
author: 'Linden Research, Inc.'

inputs:
  packages:
    description: 'Cygwin packages to install'
  site:
    description: 'Package mirror URL'
    default: 'https://mirrors.kernel.org/sourceware/cygwin/'
  root:
    description: 'Installation location'
    default: 'C:\cygwin64'
  local-packages:
    description: 'Package download directory'
    default: 'C:\TEMP\cygwinpackages'

outputs:
  bash:
    description: 'Cygwin shell'
    value: ${{ inputs.root }}\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

runs:
  using: 'node12'
  main: 'dist/index.js'
