name: 'build-test'
on: 
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: windows-2022 
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: cygwin
        with:
          packages: curl,patch
      - name: Run shell
        run: |
          ls
          echo "hello"
        shell: ${{ steps.cygwin.outputs.bash }}
